from . import hs_code
from . import product_template
from . import sale_order
from . import purchase_order
from . import account_move
from . import product_product
from . import res_partner
from . import stock_move
from . import stock_move_line
